[package]
name = "r2-file-explorer-worker"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
worker = "0.6.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "1.0", features = ["v4", "serde", "js"] }
console_error_panic_hook = "0.1"
wasm-bindgen = "0.2"

# JWT support will be added later with a WebAssembly-compatible library
# jsonwebtoken = { version = "9.2", default-features = false }
