name = "r2-file-explorer-api"
main = "pkg/r2_file_explorer_worker.js"
compatibility_date = "2024-01-01"

# R2 bucket binding for file storage
[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "file-explorer-storage"

# KV namespace for session storage
[[kv_namespaces]]
binding = "KV_SESSIONS"
id = "session-storage-namespace"
preview_id = "session-storage-namespace-preview"

# Analytics Engine binding for observability (disabled in local dev)
# [[analytics_engine_datasets]]
# binding = "ANALYTICS"

# Development environment variables
[vars]
JWT_SECRET = "dev-secret-key-for-local-development-only-not-secure"
CORS_ORIGINS = "http://localhost:5173,http://127.0.0.1:5173,http://localhost:3000"
JWT_EXPIRY_HOURS = "24"
MAX_FILE_SIZE_MB = "50"
ENVIRONMENT = "development"

# Staging environment configuration
[env.staging]
name = "r2-file-explorer-api-staging"

[env.staging.vars]
JWT_SECRET = "REPLACE_WITH_SECURE_STAGING_SECRET"
CORS_ORIGINS = "https://r2-file-explorer-staging.pages.dev"
JWT_EXPIRY_HOURS = "12"
MAX_FILE_SIZE_MB = "100"
ENVIRONMENT = "staging"

# Production environment configuration
[env.production]
name = "r2-file-explorer-api-prod"

[env.production.vars]
JWT_SECRET = "REPLACE_WITH_SECURE_PRODUCTION_SECRET"
CORS_ORIGINS = "https://r2-file-explorer.pages.dev"
JWT_EXPIRY_HOURS = "8"
MAX_FILE_SIZE_MB = "200"
ENVIRONMENT = "production"