# Common configuration for all environments
name = "r2-file-explorer-api"
main = "src/index.ts"
compatibility_date = "2024-01-01"

# Development environment configuration (default)
[env.development]
name = "r2-file-explorer-api-dev"

# Static assets configuration for React frontend
[env.development.assets]
directory = "../frontend/dist"
binding = "ASSETS"
# Uncomment the line below if you want to use an R2 bucket for assets instead of local files
#bucket = "file-explorer-assets-dev"

# Development R2 bucket binding for file storage
[[env.development.r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "file-explorer-storage-dev"

# Development KV namespace for session storage
[[env.development.kv_namespaces]]
binding = "KV_SESSIONS"
id = "bfb16d1884344643901fd2c5d4deff36"
preview_id = "f1cab526fd664bc2bdb09efa966065b9"

# Development Analytics Engine binding for observability
[[env.development.analytics_engine_datasets]]
binding = "ANALYTICS"
dataset = "r2_file_explorer_analytics_dev"

# Development environment variables
[env.development.vars]
JWT_EXPIRY_HOURS = "24"
MAX_FILE_SIZE_MB = "50"
ENVIRONMENT = "development"
LOG_LEVEL = "debug"

# SECURITY CONFIGURATION:
# See ../SECURITY.md for complete setup instructions and best practices
#
# Quick setup: Run ./scripts/setup-secrets.sh
#
# Required secrets:
# - JWT_SECRET: For JWT token signing (32+ chars)
# - CREDENTIAL_ENCRYPTION_KEY: For AES-256 credential encryption (32+ chars)
# - CREDENTIAL_ENCRYPTION_KEY_BACKUP: For key rotation support (optional, 32+ chars)
#
# Set via: wrangler secret put <SECRET_NAME> --env <environment>

# Staging environment configuration
[env.staging]
name = "r2-file-explorer-api-staging"

# Staging R2 bucket binding
[[env.staging.r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "file-explorer-storage-staging"

# Staging KV namespace binding
[[env.staging.kv_namespaces]]
binding = "KV_SESSIONS"
id = "file-explorer-sessions-staging"
preview_id = "file-explorer-sessions-staging-preview"

# Staging Analytics Engine binding
[[env.staging.analytics_engine_datasets]]
binding = "ANALYTICS"
dataset = "r2_file_explorer_analytics_staging"

[env.staging.vars]
# Secrets: See ../SECURITY.md for setup instructions
JWT_EXPIRY_HOURS = "12"
MAX_FILE_SIZE_MB = "100"
ENVIRONMENT = "staging"

# Production environment configuration
[env.production]
name = "r2-file-explorer-api-prod"

# Production R2 bucket binding
[[env.production.r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "file-explorer-storage-prod"

# Production KV namespace binding
[[env.production.kv_namespaces]]
binding = "KV_SESSIONS"
id = "file-explorer-sessions-prod"
preview_id = "file-explorer-sessions-prod-preview"

# Production Analytics Engine binding
[[env.production.analytics_engine_datasets]]
binding = "ANALYTICS"
dataset = "r2_file_explorer_analytics_prod"

[env.production.vars]
# Secrets: See ../SECURITY.md for setup instructions
JWT_EXPIRY_HOURS = "8"
MAX_FILE_SIZE_MB = "200"
ENVIRONMENT = "production"