name = "r2-file-explorer-api"
main = "pkg/r2_file_explorer_worker.js"
compatibility_date = "2024-01-01"

# R2 bucket binding for file storage
[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "file-explorer-storage"

# KV namespace for session storage
[[kv_namespaces]]
binding = "KV_SESSIONS"
id = "session-storage-namespace"
preview_id = "session-storage-namespace-preview"

# Analytics Engine binding for observability (disabled in local dev)
# [[analytics_engine_datasets]]
# binding = "ANALYTICS"

# Development environment variables
[vars]
JWT_SECRET = "dev-jwt-secret-change-in-production"
CORS_ORIGINS = "http://localhost:5173,http://127.0.0.1:5173"
JWT_EXPIRY_HOURS = "24"
MAX_FILE_SIZE_MB = "100"
ENVIRONMENT = "development"

# Production environment configuration
[env.production]
name = "r2-file-explorer-api-prod"

[env.production.vars]
JWT_SECRET = "production-jwt-secret-change-this"
CORS_ORIGINS = "https://your-production-domain.pages.dev"
JWT_EXPIRY_HOURS = "8"
MAX_FILE_SIZE_MB = "500"
ENVIRONMENT = "production"

# Staging environment configuration
[env.staging]
name = "r2-file-explorer-api-staging"

[env.staging.vars]
JWT_SECRET = "staging-jwt-secret-change-this"
CORS_ORIGINS = "https://staging-domain.pages.dev"
JWT_EXPIRY_HOURS = "12"
MAX_FILE_SIZE_MB = "200"
ENVIRONMENT = "staging"