# Common configuration for all environments
name = "r2-file-explorer-api"
main = "src/index.ts"
compatibility_date = "2024-01-01"

# Development environment configuration (default)
[env.development]
name = "r2-file-explorer-api-dev"

# Static assets configuration for React frontend
[env.development.assets]
directory = "../frontend/dist"
binding = "ASSETS"
bucket = "file-explorer-assets-dev"

# Development R2 bucket binding for file storage
[[env.development.r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "file-explorer-storage-dev"

# Development KV namespace for session storage
[[env.development.kv_namespaces]]
binding = "KV_SESSIONS"
id = "file-explorer-sessions-dev"
preview_id = "file-explorer-sessions-dev-preview"

# Development Analytics Engine binding for observability
[[env.development.analytics_engine_datasets]]
binding = "ANALYTICS"
dataset = "r2_file_explorer_analytics_dev"

# Development environment variables
[env.development.vars]
JWT_EXPIRY_HOURS = "24"
MAX_FILE_SIZE_MB = "50"
ENVIRONMENT = "development"

# Note: JWT_SECRET should be set via wrangler secret for security
# Run: wrangler secret put JWT_SECRET --env development

# Staging environment configuration
[env.staging]
name = "r2-file-explorer-api-staging"

# Staging R2 bucket binding
[[env.staging.r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "file-explorer-storage-staging"

# Staging KV namespace binding
[[env.staging.kv_namespaces]]
binding = "KV_SESSIONS"
id = "file-explorer-sessions-staging"
preview_id = "file-explorer-sessions-staging-preview"

# Staging Analytics Engine binding
[[env.staging.analytics_engine_datasets]]
binding = "ANALYTICS"
dataset = "r2_file_explorer_analytics_staging"

[env.staging.vars]
JWT_SECRET = "REPLACE_WITH_SECURE_STAGING_SECRET"
JWT_EXPIRY_HOURS = "12"
MAX_FILE_SIZE_MB = "100"
ENVIRONMENT = "staging"

# Production environment configuration
[env.production]
name = "r2-file-explorer-api-prod"

# Production R2 bucket binding
[[env.production.r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "file-explorer-storage-prod"

# Production KV namespace binding
[[env.production.kv_namespaces]]
binding = "KV_SESSIONS"
id = "file-explorer-sessions-prod"
preview_id = "file-explorer-sessions-prod-preview"

# Production Analytics Engine binding
[[env.production.analytics_engine_datasets]]
binding = "ANALYTICS"
dataset = "r2_file_explorer_analytics_prod"

[env.production.vars]
JWT_SECRET = "REPLACE_WITH_SECURE_PRODUCTION_SECRET"
JWT_EXPIRY_HOURS = "8"
MAX_FILE_SIZE_MB = "200"
ENVIRONMENT = "production"