name = "r2-file-explorer-api"
main = "src/lib.rs"
compatibility_date = "2024-01-01"

[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "file-explorer-storage"

[[kv_namespaces]]
binding = "KV_SESSIONS"
id = "session-storage-namespace"
preview_id = "session-storage-namespace-preview"

[vars]
JWT_SECRET = "your-jwt-secret-change-in-production"
CORS_ORIGINS = "http://localhost:5173,https://your-frontend-domain.pages.dev"

[env.production]
name = "r2-file-explorer-api-prod"

[env.production.vars]
JWT_SECRET = "production-jwt-secret"
CORS_ORIGINS = "https://your-production-domain.pages.dev"